theme: jekyll-theme-minimal

title: Zhang, Feng
logo: /img/photo.JPG
description: PhD student in Biostatistics, Fudan University; Graduate Assistant, Cincinnati Children’s Hospital Medical Center; Email: fzhang15@fudan.edu.cn
show_downloads: false
google_analytics:

